version: '3'
services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
#    networks:
#      - almond-be_almond-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
#    networks:
#      - almond-be_almond-network

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
#    networks:
#      - almond-be_almond-network

#networks:
#  almond-be_almond-network:
#    external: true
